// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'attribution': string;
  'description': string;
  'header': string;
  'name': string;
  'source': string;
  'status': string;
}
export const cssExports: CssExports;
export default cssExports;
